CREATE SCHEMA EXERCICIO3_DDL;
USE EXERCICIO3_DDL;

-- Tabela CLIENTES
CREATE TABLE IF NOT EXISTS CLIENTES (
    ID_CLI INT PRIMARY KEY,
    CNPJ_CLI VARCHAR(14) NOT NULL,
    RAZAO_CLI VARCHAR(100) NOT NULL,
    RAMO_CLI VARCHAR(100),
    DT_CAD_CLI DATE NOT NULL,
    CONTATO_CLI VARCHAR(100)
);

-- Tabela TELEFONES_CLIENTES (Multivalorado)
CREATE TABLE IF NOT EXISTS TEL_CLIENTES (
    ID_CLI INT,
    TEL_CLI VARCHAR(15),
    PRIMARY KEY (ID_CLI, TEL_CLI),
    FOREIGN KEY (ID_CLI) REFERENCES CLIENTES(ID_CLI)
);

-- Tabela EMPREGADOS
CREATE TABLE IF NOT EXISTS EMPREGADOS (
    ID_EMP INT PRIMARY KEY,
    NOME_EMP VARCHAR(100) NOT NULL,
    CARGO_EMP VARCHAR(50),
    SAL_EMP DECIMAL(10, 2),
    DT_ADM_EMP DATE,
    QUALIF_EMP TEXT
);

-- Tabela TELEFONES_EMPREGADOS (Multivalorado)
CREATE TABLE IF NOT EXISTS TEL_EMPREGADOS (
    ID_EMP INT,
    TEL_EMP VARCHAR(15),
    PRIMARY KEY (ID_EMP, TEL_EMP),
    FOREIGN KEY (ID_EMP) REFERENCES EMPREGADOS(ID_EMP)
);

-- Tabela EMPRESAS
CREATE TABLE IF NOT EXISTS EMPRESAS (
    CNPJ_EMP VARCHAR(14) PRIMARY KEY,
    RAZAO_EMP VARCHAR(100) NOT NULL,
    CONTATO_EMP VARCHAR(100)
);

-- Tabela FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES (
    CNPJ_FORN VARCHAR(14) PRIMARY KEY,
    RAZAO_FORN VARCHAR(100) NOT NULL,
    CONTATO_FORN VARCHAR(100)
);

-- Tabela TIPO_ENDERECO
CREATE TABLE IF NOT EXISTS TIPO_ENDERECO (
    ID_TIP_END INT PRIMARY KEY,
    NOME_TIP_END VARCHAR(50) NOT NULL
);

-- Tabela ENDERECOS
CREATE TABLE IF NOT EXISTS ENDERECOS (
    ID_END INT PRIMARY KEY,
    NUM_END INT NOT NULL,
    LOGR_END VARCHAR(100) NOT NULL,
    COMPL_END VARCHAR(50),
    CEP_END VARCHAR(10) NOT NULL,
    BAIRRO_END VARCHAR(50) NOT NULL,
    CIDADE_END VARCHAR(50) NOT NULL,
    ESTADO_END VARCHAR(2) NOT NULL,
    ID_TIP_END INT,
    FOREIGN KEY (ID_TIP_END) REFERENCES TIPO_ENDERECO(ID_TIP_END)
);

-- Tabela ENCOMENDAS
CREATE TABLE IF NOT EXISTS ENCOMENDAS (
    NUM_ENC INT PRIMARY KEY,
    DT_INCL_ENC DATE NOT NULL,
    VLR_TOT_ENC DECIMAL(10, 2),
    VLR_DESC_ENC DECIMAL(10, 2),
    VLR_LIQ_ENC DECIMAL(10, 2),
    ID_FORMA_PAG INT,
    QT_PARC_ENC INT,
    ID_CLI INT NOT NULL,
    FOREIGN KEY (ID_CLI) REFERENCES CLIENTES(ID_CLI)
);

-- Tabela PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS (
    ID_PROD INT PRIMARY KEY,
    NOME_PROD VARCHAR(100),
    COR_PROD VARCHAR(30),
    DIM_PROD VARCHAR(50),
    PESO_PROD DECIMAL(10, 2),
    PRECO_PROD DECIMAL(10, 2),
    TMP_FAB_PROD INT,
    DESENHO_PROD BLOB,
    HORAS_MO_PROD INT
);

-- Tabela TIPOS_COMPONENTE
CREATE TABLE IF NOT EXISTS TIPOS_COMPONENTE (
    ID_TIP_COMP INT PRIMARY KEY,
    NOME_TIP_COMP VARCHAR(100)
);

-- Tabela COMPONENTES
CREATE TABLE IF NOT EXISTS COMPONENTES (
    ID_COMP INT PRIMARY KEY,
    NOME_COMP VARCHAR(100),
    QTD_ESTOQUE_COMP INT,
    PRECO_UN_COMP DECIMAL(10, 2),
    UNID_COMP VARCHAR(10),
    ID_TIP_COMP INT,
    FOREIGN KEY (ID_TIP_COMP) REFERENCES TIPOS_COMPONENTE(ID_TIP_COMP)
);

-- Tabela MAQUINAS
CREATE TABLE IF NOT EXISTS MAQUINAS (
    ID_MAQ INT PRIMARY KEY,
    TMP_VIDA_MAQ INT,
    DT_COMPRA_MAQ DATE,
    DT_FIM_GAR_MAQ DATE
);

-- Tabela RECURSOS_ESPECIFICOS (Recursos Específicos)
CREATE TABLE IF NOT EXISTS REC_ESPECIFICOS (
    ID_RE INT PRIMARY KEY,
    QTD_NEC_RE INT,
    UNID_RE VARCHAR(10),
    TMP_USO_RE INT,
    HORAS_MO_RE INT
);

-- Tabela REGISTRO_MANUTENCAO
CREATE TABLE IF NOT EXISTS REG_MANUT (
    ID_REG_MAN INT PRIMARY KEY,
    DT_MAN DATE,
    DESC_MAN TEXT,
    ID_MAQ INT,
    FOREIGN KEY (ID_MAQ) REFERENCES MAQUINAS(ID_MAQ)
);

-- Tabela REGISTRO_SUPRIMENTOS
CREATE TABLE IF NOT EXISTS REG_SUPRIMENTOS (
    ID_REG_SUP INT PRIMARY KEY,
    QTD_SUP INT,
    DT_NEC_SUP DATE,
    ID_COMP INT,
    FOREIGN KEY (ID_COMP) REFERENCES COMPONENTES(ID_COMP)
);

CREATE SCHEMA EXERCICIO3_DDL;
USE EXERCICIO3_DDL;

-- Tabela CLIENTES
CREATE TABLE IF NOT EXISTS CLIENTES (
    ID_CLI INT PRIMARY KEY,
    CNPJ_CLI VARCHAR(14) NOT NULL,
    RAZAO_CLI VARCHAR(100) NOT NULL,
    RAMO_CLI VARCHAR(100),
    DT_CAD_CLI DATE NOT NULL,
    CONTATO_CLI VARCHAR(100)
);

-- Tabela TELEFONES_CLIENTES (Multivalorado)
CREATE TABLE IF NOT EXISTS TEL_CLIENTES (
    ID_CLI INT,
    TEL_CLI VARCHAR(15),
    PRIMARY KEY (ID_CLI, TEL_CLI),
    FOREIGN KEY (ID_CLI) REFERENCES CLIENTES(ID_CLI)
);

-- Tabela EMPREGADOS
CREATE TABLE IF NOT EXISTS EMPREGADOS (
    ID_EMP INT PRIMARY KEY,
    NOME_EMP VARCHAR(100) NOT NULL,
    CARGO_EMP VARCHAR(50),
    SAL_EMP DECIMAL(10, 2),
    DT_ADM_EMP DATE,
    QUALIF_EMP TEXT
);

-- Tabela TELEFONES_EMPREGADOS (Multivalorado)
CREATE TABLE IF NOT EXISTS TEL_EMPREGADOS (
    ID_EMP INT,
    TEL_EMP VARCHAR(15),
    PRIMARY KEY (ID_EMP, TEL_EMP),
    FOREIGN KEY (ID_EMP) REFERENCES EMPREGADOS(ID_EMP)
);

-- Tabela EMPRESAS
CREATE TABLE IF NOT EXISTS EMPRESAS (
    CNPJ_EMP VARCHAR(14) PRIMARY KEY,
    RAZAO_EMP VARCHAR(100) NOT NULL,
    CONTATO_EMP VARCHAR(100)
);

-- Tabela FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES (
    CNPJ_FORN VARCHAR(14) PRIMARY KEY,
    RAZAO_FORN VARCHAR(100) NOT NULL,
    CONTATO_FORN VARCHAR(100)
);

-- Tabela TIPO_ENDERECO
CREATE TABLE IF NOT EXISTS TIPO_ENDERECO (
    ID_TIP_END INT PRIMARY KEY,
    NOME_TIP_END VARCHAR(50) NOT NULL
);

-- Tabela ENDERECOS
CREATE TABLE IF NOT EXISTS ENDERECOS (
    ID_END INT PRIMARY KEY,
    NUM_END INT NOT NULL,
    LOGR_END VARCHAR(100) NOT NULL,
    COMPL_END VARCHAR(50),
    CEP_END VARCHAR(10) NOT NULL,
    BAIRRO_END VARCHAR(50) NOT NULL,
    CIDADE_END VARCHAR(50) NOT NULL,
    ESTADO_END VARCHAR(2) NOT NULL,
    ID_TIP_END INT,
    FOREIGN KEY (ID_TIP_END) REFERENCES TIPO_ENDERECO(ID_TIP_END)
);

-- Tabela ENCOMENDAS
CREATE TABLE IF NOT EXISTS ENCOMENDAS (
    NUM_ENC INT PRIMARY KEY,
    DT_INCL_ENC DATE NOT NULL,
    VLR_TOT_ENC DECIMAL(10, 2),
    VLR_DESC_ENC DECIMAL(10, 2),
    VLR_LIQ_ENC DECIMAL(10, 2),
    ID_FORMA_PAG INT,
    QT_PARC_ENC INT,
    ID_CLI INT NOT NULL,
    FOREIGN KEY (ID_CLI) REFERENCES CLIENTES(ID_CLI)
);

-- Tabela PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS (
    ID_PROD INT PRIMARY KEY,
    NOME_PROD VARCHAR(100),
    COR_PROD VARCHAR(30),
    DIM_PROD VARCHAR(50),
    PESO_PROD DECIMAL(10, 2),
    PRECO_PROD DECIMAL(10, 2),
    TMP_FAB_PROD INT,
    DESENHO_PROD BLOB,
    HORAS_MO_PROD INT
);

-- Tabela TIPOS_COMPONENTE
CREATE TABLE IF NOT EXISTS TIPOS_COMPONENTE (
    ID_TIP_COMP INT PRIMARY KEY,
    NOME_TIP_COMP VARCHAR(100)
);

-- Tabela COMPONENTES
CREATE TABLE IF NOT EXISTS COMPONENTES (
    ID_COMP INT PRIMARY KEY,
    NOME_COMP VARCHAR(100),
    QTD_ESTOQUE_COMP INT,
    PRECO_UN_COMP DECIMAL(10, 2),
    UNID_COMP VARCHAR(10),
    ID_TIP_COMP INT,
    FOREIGN KEY (ID_TIP_COMP) REFERENCES TIPOS_COMPONENTE(ID_TIP_COMP)
);

-- Tabela MAQUINAS
CREATE TABLE IF NOT EXISTS MAQUINAS (
    ID_MAQ INT PRIMARY KEY,
    TMP_VIDA_MAQ INT,
    DT_COMPRA_MAQ DATE,
    DT_FIM_GAR_MAQ DATE
);

-- Tabela RECURSOS_ESPECIFICOS (Recursos Específicos)
CREATE TABLE IF NOT EXISTS REC_ESPECIFICOS (
    ID_RE INT PRIMARY KEY,
    QTD_NEC_RE INT,
    UNID_RE VARCHAR(10),
    TMP_USO_RE INT,
    HORAS_MO_RE INT
);

-- Tabela REGISTRO_MANUTENCAO
CREATE TABLE IF NOT EXISTS REG_MANUT (
    ID_REG_MAN INT PRIMARY KEY,
    DT_MAN DATE,
    DESC_MAN TEXT,
    ID_MAQ INT,
    FOREIGN KEY (ID_MAQ) REFERENCES MAQUINAS(ID_MAQ)
);

-- Tabela REGISTRO_SUPRIMENTOS
CREATE TABLE IF NOT EXISTS REG_SUPRIMENTOS (
    ID_REG_SUP INT PRIMARY KEY,
    QTD_SUP INT,
    DT_NEC_SUP DATE,
    ID_COMP INT,
    FOREIGN KEY (ID_COMP) REFERENCES COMPONENTES(ID_COMP)
);
