CREATE SCHEMA EXERCICIO4_DDL;
USE EXERCICIO4_DDL;

CREATE TABLE IF NOT EXISTS ALUNOS (
    ID_ALU INT PRIMARY KEY,
    NOME_ALU VARCHAR(100) NOT NULL,
    CPF_ALU VARCHAR(11) NOT NULL,
    DT_NASC_ALU DATE NOT NULL,
    END_ALU VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS INSTRUTORES (
    ID_INST INT PRIMARY KEY,
    NOME_INST VARCHAR(100) NOT NULL,
    CPF_INST VARCHAR(11) NOT NULL,
    DT_CONTRATO_INST DATE,
    MOD_INST VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS MODALIDADES (
    ID_MOD INT PRIMARY KEY,
    NOME_MOD VARCHAR(100) NOT NULL,
    DESC_MOD TEXT
);

CREATE TABLE IF NOT EXISTS MATRICULAS (
    ID_ALU INT,
    ID_MOD INT,
    PRIMARY KEY (ID_ALU, ID_MOD),
    FOREIGN KEY (ID_ALU) REFERENCES ALUNOS(ID_ALU),
    FOREIGN KEY (ID_MOD) REFERENCES MODALIDADES(ID_MOD)
);

CREATE TABLE IF NOT EXISTS PLANOS_TREINO (
    ID_PLANO INT PRIMARY KEY,
    DESC_PLANO TEXT NOT NULL,
    ID_ALU INT,
    ID_INST INT,
    FOREIGN KEY (ID_ALU) REFERENCES ALUNOS(ID_ALU),
    FOREIGN KEY (ID_INST) REFERENCES INSTRUTORES(ID_INST)
);

CREATE TABLE IF NOT EXISTS AULAS (
    ID_AULA INT PRIMARY KEY,
    DT_HORA_AULA DATETIME NOT NULL,
    CAP_MAX_AULA INT,
    ID_INST INT,
    ID_MOD INT,
    FOREIGN KEY (ID_INST) REFERENCES INSTRUTORES(ID_INST),
    FOREIGN KEY (ID_MOD) REFERENCES MODALIDADES(ID_MOD)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
    ID_PAG INT PRIMARY KEY,
    DT_PAG DATE NOT NULL,
    VLR_PAG DECIMAL(10, 2) NOT NULL,
    STATUS_PAG VARCHAR(10) CHECK (STATUS_PAG IN ('Pago', 'Pendente')),
    ID_ALU INT,
    FOREIGN KEY (ID_ALU) REFERENCES ALUNOS(ID_ALU)
);

CREATE TABLE IF NOT EXISTS PARTICIPACOES (
    ID_ALU INT,
    ID_AULA INT,
    PRIMARY KEY (ID_ALU, ID_AULA),
    FOREIGN KEY (ID_ALU) REFERENCES ALUNOS(ID_ALU),
    FOREIGN KEY (ID_AULA) REFERENCES AULAS(ID_AULA)
);

ALTER TABLE INSTRUTORES
ADD EMAIL_INST VARCHAR(100);

ALTER TABLE PLANOS_TREINO
MODIFY DESC_PLANO VARCHAR(255);

DROP TABLE IF EXISTS PARTICIPACOES;
