CREATE SCHEMA EXERCICIO5_DDL;
USE EXERCICIO5_DDL;

CREATE TABLE IF NOT EXISTS CLIENTES (
    CLIENTE_ID INT PRIMARY KEY,
    CLIENTE_NOME VARCHAR(45) NOT NULL,
    CLIENTE_CPF VARCHAR(11) NOT NULL,
    CLIENTE_DATA_NASC DATE NOT NULL,
    CLIENTE_RUA VARCHAR(100) NOT NULL,
    CLIENTE_NUMRUA INT NOT NULL,
    CLIENTE_BAIRRO VARCHAR(45) NOT NULL,
    CLIENTE_CIDADE VARCHAR(45) NOT NULL,
    CLIENTE_ESTADO VARCHAR(45) NOT NULL,
    CLIENTE_PAIS VARCHAR(30) NOT NULL,
    CLIENTE_CODPOSTAL VARCHAR(10) NOT NULL,
    CLIENTE_TELEFONE VARCHAR(15) NOT NULL,
    CLIENTE_PROGRAMA_FIDELIDADE ENUM('S', 'N') NOT NULL
);
CREATE TABLE IF NOT EXISTS FORNECEDORES (
    FORNEC_COD INT PRIMARY KEY,
    FORNEC_NOME VARCHAR(45) NOT NULL,
    FORNEC_RUA VARCHAR(45) NOT NULL,
    FORNEC_NUMRUA INT,
    FORNEC_BAIRRO VARCHAR(45) NOT NULL,
    FORNEC_CIDADE VARCHAR(45) NOT NULL,
    FORNEC_ESTADO VARCHAR(45) NOT NULL,
    FORNEC_PAIS VARCHAR(30) NOT NULL,
    FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
    FORNEC_TELEFONE VARCHAR(15) NOT NULL,
    FORNEC_CONTATO TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS PRODUTOS (
    PROD_COD INT PRIMARY KEY,
    PROD_NOME VARCHAR(50) NOT NULL,
    PROD_DESCRICAO TEXT NOT NULL,
    PROD_ESPECTEC TEXT NOT NULL,
    PROD_QUANT DECIMAL(10,3) NOT NULL,
    PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
    PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
    PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);
CREATE TABLE IF NOT EXISTS VENDAS (
    VENDA_COD INT PRIMARY KEY,
    VENDA_DATA DATE NOT NULL,
    VENDA_HORA TIME NOT NULL,
    VENDA_STATUS ENUM('PENDENTE', 'CONCLUÍDO', 'CANCELADO') NOT NULL,
    VENDA_CLIENTE_ID INT NOT NULL,
    CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (VENDA_CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);
CREATE TABLE IF NOT EXISTS PAGAMENTOS (
    PAGAMENTO_COD INT PRIMARY KEY,
    PAGAMENTO_VALOR DECIMAL(10,2) NOT NULL,
    PAGAMENTO_DATA DATE NOT NULL,
    PAGAMENTO_STATUS ENUM('PAGO', 'PENDENTE') NOT NULL,
    PAGAMENTO_VENDA_ID INT NOT NULL,
    CONSTRAINT FK_PAGAMENTO_VENDA FOREIGN KEY (PAGAMENTO_VENDA_ID) REFERENCES VENDAS(VENDA_COD)
);
CREATE TABLE IF NOT EXISTS VENDAS_PRODUTOS (
    VP_VENDA_COD INT,
    VP_PROD_COD INT,
    VP_QUANT DECIMAL(10,3) NOT NULL,
    PRIMARY KEY(VP_VENDA_COD, VP_PROD_COD),
    CONSTRAINT FK_VP_VENDA FOREIGN KEY(VP_VENDA_COD) REFERENCES VENDAS(VENDA_COD),
    CONSTRAINT FK_VP_PROD FOREIGN KEY(VP_PROD_COD) REFERENCES PRODUTOS(PROD_COD)
);
CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS (
    FRPR_FORNECEDOR INT,
    FRPR_PRODUTO INT,
    PRIMARY KEY(FRPR_FORNECEDOR, FRPR_PRODUTO),
    CONSTRAINT FK_FRPR_FORNECEDOR FOREIGN KEY(FRPR_FORNECEDOR) REFERENCES FORNECEDORES(FORNEC_COD),
    CONSTRAINT FK_FRPR_PRODUTO FOREIGN KEY(FRPR_PRODUTO) REFERENCES PRODUTOS(PROD_COD)
);
ALTER TABLE CLIENTES
ADD CLIENTE_DATA_ADESAO DATE;

ALTER TABLE FORNECEDORES
DROP COLUMN FORNEC_CONTATO;

ALTER TABLE FILIAIS
MODIFY FILIAL_CAPACIDADE INT NOT NULL;

ALTER TABLE PRODUTOS
CHANGE PROD_PRECOUNIT PROD_PRECO_VENDA DECIMAL(10,2) NOT NULL;

ALTER TABLE PEDIDOS
ADD PED_METODO_PAGAMENTO VARCHAR(20) NOT NULL;

ALTER TABLE RECEBIMENTOS
DROP COLUMN RECEB_CONDICAO;

ALTER TABLE PEDIDOS_PRODUTOS
MODIFY PDPR_QUANT DECIMAL(12,3) NOT NULL;

ALTER TABLE FORNECEDORES_PRODUTOS
ADD FRPR_DATA_ULTIMO_PEDIDO DATE;

